import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { api, token } from "../api";
import type { GameHistoryItem, UserStats } from "@hanabi/protocol";
interface Me { user:{id:string;username:string}; stats:UserStats; history:GameHistoryItem[]; activeRoomCode?:string }
function duration(seconds:number){const h=Math.floor(seconds/3600),m=Math.floor(seconds%3600/60);return h?`${h}小时 ${m}分钟`:`${m}分钟`;}
export function DashboardPage(){ const [me,setMe]=useState<Me>(); const [roomName,setRoomName]=useState("花火之夜"); const [code,setCode]=useState(""); const [error,setError]=useState(""); const navigate=useNavigate(); useEffect(()=>{api<Me>("/api/me").then(setMe).catch(()=>{token.clear();navigate("/login")})},[]);
 async function create(){try{const r=await api<{code:string}>("/api/rooms",{method:"POST",body:JSON.stringify({name:roomName})});navigate(`/room/${r.code}`)}catch(e){setError((e as Error).message)}}
 async function join(){try{const r=await api<{code:string}>(`/api/rooms/${code.toUpperCase()}/join`,{method:"POST"});navigate(`/room/${r.code}`)}catch(e){setError((e as Error).message)}}
 if(!me)return <div className="loading">正在点燃引线…</div>;
 return <main className="dashboard"><header className="topbar"><div className="logo"><span className="logo-burst"/>花火</div><div className="user-menu"><span>{me.user.username}</span><button onClick={()=>{token.clear();navigate("/login")}}>退出</button></div></header><div className="dashboard-grid"><section><p className="eyebrow">欢迎回来，{me.user.username}</p><h1>今晚，点亮怎样的烟火？</h1>{me.activeRoomCode&&<button className="resume" onClick={()=>navigate(`/room/${me.activeRoomCode}`)}>继续未完成的对局 <b>{me.activeRoomCode}</b></button>}<div className="room-actions"><article><h2>创建房间</h2><p>邀请 1–4 位朋友加入你的牌桌。</p><input value={roomName} onChange={e=>setRoomName(e.target.value)}/><button className="primary" onClick={create}>创建新牌桌</button></article><article><h2>加入房间</h2><p>输入朋友分享的六位房间码。</p><input className="code-input" maxLength={6} value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="ABC234"/><button className="secondary" onClick={join}>加入牌桌</button></article></div>{error&&<p className="error">{error}</p>}</section><aside className="profile-panel"><h2>我的记录</h2><div className="stats"><div><strong>{me.stats.gamesPlayed}</strong><span>完成对局</span></div><div><strong>{me.stats.averageScore}</strong><span>平均得分</span></div><div><strong>{me.stats.bestScore}</strong><span>最佳得分</span></div><div><strong>{duration(me.stats.totalPlaySeconds)}</strong><span>游戏时间</span></div></div></aside></div><section className="history"><h2>历史对局</h2>{!me.history.length?<div className="empty">还没有历史记录。创建第一场烟花表演吧。</div>:<div className="history-list">{me.history.map(g=><article key={g.id}><div className={`score-badge ${g.outcome}`}>{g.score}</div><div><strong>{g.roomName}</strong><p>{g.players.join(" · ")}</p></div><div className="history-meta"><span>{new Date(g.endedAt).toLocaleDateString()}</span><span>{duration(g.durationSeconds)}</span></div></article>)}</div>}</section></main> }
